
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types';

const SUPABASE_URL = "https://qlaoyjgdnggjzxnfwwxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsYW95amdkbmdnanp4bmZ3d3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTIzNzQsImV4cCI6MjA2MTA4ODM3NH0.G402CjCjdzqD_Y4SVB_Ry1LHWVhJScO4oEAlb8C9_8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
